import{getAllRecords,getRecordsByDateRange,addRecord,getAllAchievements}from'../../src/db/crud.js';console.log('📊 历史记录页面初始化...');class HistoryPage{constructor(){this.currentView='week';this.currentDate=new Date();this.records=[];this.stats={totalCups:0,avgDailyCups:0,maxStreakDays:0,achievementsCount:0};this.init();}
async init(){console.log('初始化历史记录页面...');this.bindEvents();await this.loadData();this.hideLoading();this.render();}
bindEvents(){const viewBtns=document.querySelectorAll('.view-btn');viewBtns.forEach(btn=>{btn.addEventListener('click',(e)=>{const view=e.target.dataset.view;this.switchView(view);});});document.getElementById('prevPeriod').addEventListener('click',()=>{this.navigatePeriod(-1);});document.getElementById('nextPeriod').addEventListener('click',()=>{this.navigatePeriod(1);});document.getElementById('applyDateRange').addEventListener('click',()=>{this.applyDateRange();});this.setDefaultDateRange();}
setDefaultDateRange(){const today=new Date();const weekAgo=new Date();weekAgo.setDate(today.getDate()-6);const startDateInput=document.getElementById('startDate');const endDateInput=document.getElementById('endDate');startDateInput.value=this.formatDateForInput(weekAgo);endDateInput.value=this.formatDateForInput(today);}
formatDateForInput(date){const year=date.getFullYear();const month=String(date.getMonth()+1).padStart(2,'0');const day=String(date.getDate()).padStart(2,'0');return`${year}-${month}-${day}`;}
async loadData(){try{this.records=await getAllRecords();console.log(`📁 获取到 ${this.records.length}条历史记录`,this.records);if(this.records.length<5&&(window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1')){console.log('🧪 开发环境：生成模拟历史数据');await this.generateMockData();this.records=await getAllRecords();}
await this.calculateStats();this.updateStatsCards();}catch(error){console.error('❌ 加载历史数据失败:',error);this.showError('加载历史数据失败，请刷新页面重试');}}
async generateMockData(){try{const today=new Date();for(let i=30;i>=0;i--){const date=new Date();date.setDate(today.getDate()-i);const dateStr=date.toISOString().split('T')[0];let cups;const dayOfWeek=date.getDay();if(dayOfWeek===0||dayOfWeek===6){cups=Math.random()<0.7?Math.floor(Math.random()*5):Math.floor(Math.random()*9);}else{cups=Math.floor(Math.random()*10)+3;}
const goal=Math.floor(Math.random()*5)+6;const weatherAdjustment=Math.floor(Math.random()*5)-2;await addRecord({date:dateStr,cups_drunk:cups,goal:goal,weather_adjustment:weatherAdjustment});console.log(`➕ 添加模拟记录:${dateStr}${cups}杯`);}
console.log('✅ 模拟数据生成完成');}catch(error){console.error('❌ 生成模拟数据失败:',error);}}
async calculateStats(){if(this.records.length===0){return;}
const totalCups=this.records.reduce((sum,record)=>{return sum+(record.cups_drunk||0);},0);const dateSet=new Set();this.records.forEach(record=>{if(record.date){dateSet.add(record.date);}});const uniqueDays=dateSet.size;const avgDailyCups=uniqueDays>0?(totalCups/uniqueDays).toFixed(1):0;const sortedDates=Array.from(dateSet).sort();let maxStreak=0;let currentStreak=0;let prevDate=null;sortedDates.forEach(dateStr=>{const date=new Date(dateStr);if(prevDate===null){currentStreak=1;}else{const diffTime=date-prevDate;const diffDays=Math.floor(diffTime/(1000*60*60*24));if(diffDays===1){currentStreak++;}else{currentStreak=1;}}
maxStreak=Math.max(maxStreak,currentStreak);prevDate=date;});let unlockedCount=0;try{const achievements=await getAllAchievements();unlockedCount=achievements.filter(a=>a.unlocked).length;console.log(`🏆 数据库中共有 ${achievements.length}个成就，已解锁 ${unlockedCount}个`);}catch(error){console.warn('无法从数据库获取成就数据，使用本地存储:',error);const achievements=JSON.parse(localStorage.getItem('water_achievements')||'[]');unlockedCount=achievements.filter(a=>a.unlocked).length;}
this.stats={totalCups,avgDailyCups,maxStreakDays:maxStreak,achievementsCount:unlockedCount};}
updateStatsCards(){document.getElementById('totalCups').textContent=this.stats.totalCups;document.getElementById('avgDailyCups').textContent=this.stats.avgDailyCups;document.getElementById('maxStreakDays').textContent=this.stats.maxStreakDays;document.getElementById('achievementsCount').textContent=this.stats.achievementsCount;}
switchView(view){if(this.currentView===view){return;}
document.querySelectorAll('.view-btn').forEach(btn=>{if(btn.dataset.view===view){btn.classList.add('active');}else{btn.classList.remove('active');}});this.currentView=view;this.renderCalendar();this.updateCalendarTitle();}
navigatePeriod(direction){if(this.currentView==='week'){this.currentDate.setDate(this.currentDate.getDate()+(direction*7));}else{this.currentDate.setMonth(this.currentDate.getMonth()+direction);}
this.renderCalendar();this.updateCalendarTitle();}
async applyDateRange(){const startDateInput=document.getElementById('startDate').value;const endDateInput=document.getElementById('endDate').value;if(!startDateInput||!endDateInput){this.showError('请选择完整的日期范围');return;}
const startDate=new Date(startDateInput);const endDate=new Date(endDateInput);const diffDays=(endDate-startDate)/(1000*60*60*24);if(diffDays<=14){this.switchView('week');}else{this.switchView('month');}
try{this.records=await getRecordsByDateRange(startDateInput,endDateInput);console.log(`📊 根据日期范围获取 ${this.records.length}条记录`,startDateInput,endDateInput);await this.calculateStats();this.updateStatsCards();this.renderCalendar();this.renderCharts();this.showToast('日期范围已更新','success');}catch(error){console.error('❌ 筛选记录失败:',error);this.showError('筛选记录失败，请重试');}}
updateCalendarTitle(){const titleEl=document.getElementById('calendarTitle');if(this.currentView==='week'){const weekStart=this.getWeekStartDate(this.currentDate);const weekEnd=new Date(weekStart);weekEnd.setDate(weekStart.getDate()+6);const formatOptions={month:'long',day:'numeric'};const startStr=weekStart.toLocaleDateString('zh-CN',formatOptions);const endStr=weekEnd.toLocaleDateString('zh-CN',formatOptions);titleEl.textContent=`本周(${startStr}-${endStr})`;}else{const month=this.currentDate.getMonth()+1;const year=this.currentDate.getFullYear();titleEl.textContent=`${year}年${month}月`;}}
getWeekStartDate(date){const day=date.getDay();const diff=date.getDate()-day+(day===0?-6:1);return new Date(date.setDate(diff));}
getWeekDates(date){const weekStart=this.getWeekStartDate(date);const weekDates=[];for(let i=0;i<7;i++){const day=new Date(weekStart);day.setDate(weekStart.getDate()+i);weekDates.push(day);}
return weekDates;}
getMonthDates(date){const year=date.getFullYear();const month=date.getMonth();const firstDay=new Date(year,month,1);const lastDay=new Date(year,month+1,0);const firstDayOfWeek=firstDay.getDay();const daysInMonth=lastDay.getDate();const calendar=[];const prevMonthLastDay=new Date(year,month,0).getDate();for(let i=0;i<firstDayOfWeek;i++){const day=new Date(year,month-1,prevMonthLastDay-firstDayOfWeek+i+1);calendar.push({date:day,isCurrentMonth:false,isEmpty:false});}
for(let i=1;i<=daysInMonth;i++){const day=new Date(year,month,i);calendar.push({date:day,isCurrentMonth:true,isEmpty:false});}
const remainingCells=42-calendar.length;for(let i=1;i<=remainingCells;i++){const day=new Date(year,month+1,i);calendar.push({date:day,isCurrentMonth:false,isEmpty:false});}
return calendar;}
render(){this.renderCalendar();this.updateCalendarTitle();this.renderCharts();}
renderCalendar(){const weekViewEl=document.getElementById('weekView');const monthViewEl=document.getElementById('monthView');if(this.currentView==='week'){weekViewEl.style.display='grid';monthViewEl.style.display='none';this.renderWeekCalendar();}else{weekViewEl.style.display='none';monthViewEl.style.display='grid';this.renderMonthCalendar();}}
renderWeekCalendar(){const weekDates=this.getWeekDates(this.currentDate);const todayStr=new Date().toISOString().split('T')[0];const weekDays=['周一','周二','周三','周四','周五','周六','周日'];const calendarEl=document.getElementById('weekView');calendarEl.innerHTML='';weekDays.forEach(dayName=>{const dayHeader=document.createElement('div');dayHeader.className='day-header';dayHeader.textContent=dayName;calendarEl.appendChild(dayHeader);});weekDates.forEach(date=>{const dateStr=date.toISOString().split('T')[0];const record=this.records.find(r=>r.date===dateStr);const cups=record?record.cups_drunk:0;const goal=record?record.goal:8;const dayCell=document.createElement('div');dayCell.className='day-cell';if(dateStr===todayStr){dayCell.classList.add('today');}
dayCell.innerHTML=`<div class="day-date">${date.getDate()}日</div><div class="day-cups">${cups}</div><div class="day-goal">/${goal}杯</div>`;calendarEl.appendChild(dayCell);});}
renderMonthCalendar(){const monthDates=this.getMonthDates(this.currentDate);const todayStr=new Date().toISOString().split('T')[0];const weekDays=['日','一','二','三','四','五','六'];const calendarEl=document.getElementById('monthView');calendarEl.innerHTML='';weekDays.forEach(dayName=>{const dayHeader=document.createElement('div');dayHeader.className='day-header';dayHeader.textContent=dayName;calendarEl.appendChild(dayHeader);});monthDates.forEach(dayInfo=>{const date=dayInfo.date;const dateStr=date.toISOString().split('T')[0];const record=this.records.find(r=>r.date===dateStr);const cups=record?record.cups_drunk:0;const dayCell=document.createElement('div');dayCell.className='day-cell';if(!dayInfo.isCurrentMonth){dayCell.classList.add('empty');}
if(dateStr===todayStr&&dayInfo.isCurrentMonth){dayCell.classList.add('today');}
dayCell.innerHTML=`<div class="day-date">${date.getDate()}</div>${dayInfo.isCurrentMonth?`<div class="day-cups">${cups}</div>`:''}`;calendarEl.appendChild(dayCell);});}
renderCharts(){this.renderTrendChart();this.renderMonthlyChart();}
renderTrendChart(){const ctx=document.getElementById('trendChart').getContext('2d');const last7Days=[];for(let i=6;i>=0;i--){const date=new Date();date.setDate(date.getDate()-i);last7Days.push(date.toISOString().split('T')[0]);}
const cupsData=last7Days.map(date=>{const record=this.records.find(r=>r.date===date);return record?record.cups_drunk:0;});const dateLabels=last7Days.map(dateStr=>{const date=new Date(dateStr);return`${date.getMonth()+1}/${date.getDate()}`;});if(this.trendChart){this.trendChart.destroy();}
this.trendChart=new Chart(ctx,{type:'line',data:{labels:dateLabels,datasets:[{label:'喝水杯数',data:cupsData,borderColor:'rgb(74, 144, 226)',backgroundColor:'rgba(74, 144, 226, 0.1)',borderWidth:3,fill:true,tension:0.4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true,position:'top'},tooltip:{mode:'index',intersect:false}},scales:{y:{beginAtZero:true,title:{display:true,text:'杯数'}},x:{title:{display:true,text:'日期'}}}}});}
renderMonthlyChart(){const ctx=document.getElementById('monthlyChart').getContext('2d');const currentYear=this.currentDate.getFullYear();const currentMonth=this.currentDate.getMonth();const firstDay=new Date(currentYear,currentMonth,1);const lastDay=new Date(currentYear,currentMonth+1,0);const daysInMonth=lastDay.getDate();const monthDates=[];for(let i=1;i<=daysInMonth;i++){const date=new Date(currentYear,currentMonth,i);monthDates.push(date.toISOString().split('T')[0]);}
const cupsData=monthDates.map(date=>{const record=this.records.find(r=>r.date===date);return record?record.cups_drunk:0;});const dateLabels=monthDates.map(dateStr=>{const date=new Date(dateStr);return date.getDate();});if(this.monthlyChart){this.monthlyChart.destroy();}
this.monthlyChart=new Chart(ctx,{type:'bar',data:{labels:dateLabels,datasets:[{label:'喝水杯数',data:cupsData,backgroundColor:'rgba(74, 144, 226, 0.7)',borderColor:'rgb(74, 144, 226)',borderWidth:1}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true,position:'top'},tooltip:{mode:'index',intersect:false}},scales:{y:{beginAtZero:true,title:{display:true,text:'杯数'}},x:{title:{display:true,text:'日期'}}}}});}
hideLoading(){const loadingSpinner=document.getElementById('loadingSpinner');if(loadingSpinner){loadingSpinner.style.display='none';}}
showError(message){alert(`错误:${message}`);}
showToast(message,type='info'){const toast=document.createElement('div');toast.className=`toast toast-${type}`;toast.textContent=message;document.body.appendChild(toast);setTimeout(()=>{toast.style.animation='slideOut 0.3s ease';setTimeout(()=>{if(toast.parentNode){document.body.removeChild(toast);}},300);},3000);}}
document.addEventListener('DOMContentLoaded',()=>{new HistoryPage();});