const CACHE_VERSION='20260210.1';const CACHE_NAME=`water-reminder-${CACHE_VERSION}`;const APP_NAME='水宝提醒';const PRECACHE_URLS=['./','./index.html','./style.css','./app.js','./manifest.json','./service-worker.js','./assets/icon-72.png','./assets/icon-96.png','./assets/icon-128.png','./assets/icon-144.png','./assets/icon-152.png','./assets/icon-192.png','./assets/icon-384.png','./assets/icon-512.png','./assets/favicon.ico','./assets/apple-touch-icon.png','./offline.html','./history.html','./history.js'];const CACHE_CONFIG={staticMaxAge:7*24*60*60*1000,apiMaxAge:60*60*1000,networkTimeout:5000};self.addEventListener('install',event=>{console.log(`[ServiceWorker]${APP_NAME}v${CACHE_VERSION}安装中...`);event.waitUntil(caches.open(CACHE_NAME).then(cache=>{console.log(`[ServiceWorker]预缓存 ${PRECACHE_URLS.length}个核心资源`);return cache.addAll(PRECACHE_URLS);}).then(()=>{console.log(`[ServiceWorker]${APP_NAME}预缓存完成`);return self.skipWaiting();}).catch(error=>{console.error(`[ServiceWorker]安装失败:`,error);}));});self.addEventListener('activate',event=>{console.log(`[ServiceWorker]${APP_NAME}v${CACHE_VERSION}激活中...`);event.waitUntil(Promise.all([cleanOldCaches(),cleanExpiredCacheEntries(),self.clients.claim()]).then(()=>{console.log(`[ServiceWorker]${APP_NAME}v${CACHE_VERSION}激活完成`);notifyClients({type:'SW_ACTIVATED',version:CACHE_VERSION});}));});self.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(event.request.method!=='GET'||url.protocol==='chrome-extension:'){return;}
if(url.pathname.includes('/api/')||url.pathname.endsWith('.json')){event.respondWith(handleApiRequest(event.request));}else if(isStaticAsset(url)){event.respondWith(handleStaticRequest(event.request));}else{event.respondWith(handleGenericRequest(event.request));}});function isStaticAsset(url){const staticExtensions=['.css','.js','.png','.jpg','.jpeg','.gif','.svg','.ico','.woff','.woff2','.ttf'];return staticExtensions.some(ext=>url.pathname.endsWith(ext));}
async function handleStaticRequest(request){const cache=await caches.open(CACHE_NAME);const cachedResponse=await cache.match(request);if(cachedResponse){updateCacheInBackground(request,cache);return cachedResponse;}
try{const networkResponse=await fetchWithTimeout(request,CACHE_CONFIG.networkTimeout);if(networkResponse&&networkResponse.status===200){const responseToCache=networkResponse.clone();cache.put(request,responseToCache);}
return networkResponse;}catch(error){console.warn(`[ServiceWorker]静态资源获取失败:${request.url}`,error);if(request.destination==='document'){const offlineResponse=await cache.match('./offline.html');if(offlineResponse)return offlineResponse;}
return new Response('网络不可用',{status:503,statusText:'Service Unavailable',headers:{'Content-Type':'text/plain'}});}}
async function handleApiRequest(request){try{const networkResponse=await fetchWithTimeout(request,CACHE_CONFIG.networkTimeout);if(networkResponse&&networkResponse.status===200){if(request.method==='GET'){const cache=await caches.open(CACHE_NAME);const responseToCache=networkResponse.clone();cache.put(request,responseToCache);}
return networkResponse;}
throw new Error(`API请求失败:${networkResponse?.status}`);}catch(error){console.warn(`[ServiceWorker]API请求失败，尝试使用缓存:${request.url}`,error);const cache=await caches.open(CACHE_NAME);const cachedResponse=await cache.match(request);if(cachedResponse){return cachedResponse;}
return new Response(JSON.stringify({error:'网络不可用',message:'请检查网络连接后重试',timestamp:new Date().toISOString()}),{status:503,headers:{'Content-Type':'application/json'}});}}
async function handleGenericRequest(request){try{const networkResponse=await fetchWithTimeout(request,CACHE_CONFIG.networkTimeout);return networkResponse;}catch(error){console.warn(`[ServiceWorker]请求失败:${request.url}`,error);const cache=await caches.open(CACHE_NAME);if(request.destination==='document'){const offlineResponse=await cache.match('./offline.html');if(offlineResponse)return offlineResponse;}
const cachedResponse=await cache.match(request);if(cachedResponse)return cachedResponse;return cache.match('./offline.html');}}
async function updateCacheInBackground(request,cache){try{const networkResponse=await fetchWithTimeout(request,CACHE_CONFIG.networkTimeout);if(networkResponse&&networkResponse.status===200){cache.put(request,networkResponse);console.log(`[ServiceWorker]后台更新缓存:${request.url}`);}}catch(error){}}
function fetchWithTimeout(request,timeout){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{reject(new Error('网络请求超时'));},timeout);fetch(request).then(response=>{clearTimeout(timer);resolve(response);}).catch(error=>{clearTimeout(timer);reject(error);});});}
async function cleanOldCaches(){const cacheKeys=await caches.keys();const oldCaches=cacheKeys.filter(key=>key.startsWith('water-reminder-')&&key!==CACHE_NAME);console.log(`[ServiceWorker]发现 ${oldCaches.length}个旧缓存`);return Promise.all(oldCaches.map(cacheName=>{console.log(`[ServiceWorker]删除旧缓存:${cacheName}`);return caches.delete(cacheName);}));}
async function cleanExpiredCacheEntries(){const cache=await caches.open(CACHE_NAME);const requests=await cache.keys();const now=Date.now();let cleanedCount=0;await Promise.all(requests.map(async request=>{const response=await cache.match(request);if(!response)return;const dateHeader=response.headers.get('date');const cacheControl=response.headers.get('cache-control');if(dateHeader){const cachedDate=new Date(dateHeader).getTime();let maxAge=CACHE_CONFIG.staticMaxAge;if(request.url.includes('/api/')){maxAge=CACHE_CONFIG.apiMaxAge;}
if(now-cachedDate>maxAge){await cache.delete(request);cleanedCount++;console.log(`[ServiceWorker]清理过期缓存:${request.url}`);}}}));if(cleanedCount>0){console.log(`[ServiceWorker]已清理 ${cleanedCount}个过期缓存条目`);}}
async function notifyClients(message){const clients=await self.clients.matchAll();clients.forEach(client=>{client.postMessage(message);});}
self.addEventListener('push',event=>{console.log('[ServiceWorker] 推送通知接收');if(!event.data){console.log('[ServiceWorker] 推送数据为空');return;}
const data=event.data.json();const options={body:data.body||'💧 该喝水啦！记得补充水分哦~',icon:'./assets/icon-192.png',badge:'./assets/icon-72.png',vibrate:[200,100,200],data:{url:data.url||'./',timestamp:data.timestamp||new Date().toISOString()},actions:[{action:'drink',title:'💧 喝了一杯'},{action:'skip',title:'⏭️ 跳过'},{action:'snooze',title:'⏰ 10分钟后'}],tag:'water-reminder',renotify:true};event.waitUntil(self.registration.showNotification(data.title||'水宝提醒',options));});self.addEventListener('notificationclick',event=>{console.log('[ServiceWorker] 通知点击:',event.action);event.notification.close();if(event.action==='drink'){event.waitUntil(clients.matchAll({type:'window'}).then(clientList=>{if(clientList.length>0){const client=clientList[0];client.postMessage({type:'DRINK_RECORDED',timestamp:new Date().toISOString()});return client.focus();}
return clients.openWindow('./');}));}else if(event.action==='skip'){event.waitUntil(clients.matchAll({type:'window'}).then(clientList=>{if(clientList.length>0){const client=clientList[0];client.postMessage({type:'REMINDER_SKIPPED',timestamp:new Date().toISOString()});}}));}else if(event.action==='snooze'){event.waitUntil(new Promise(resolve=>{setTimeout(()=>{self.registration.showNotification('水宝提醒',{body:'⏰ 10分钟到了，该喝水啦！',icon:'./assets/icon-192.png',tag:'water-reminder-snooze'});resolve();},10*60*1000);}));}else{event.waitUntil(clients.openWindow('./'));}});self.addEventListener('message',event=>{console.log('[ServiceWorker] 收到消息:',event.data);if(event.data.type==='SKIP_WAITING'){self.skipWaiting();}
if(event.data.type==='UPDATE_CACHE'){caches.open(CACHE_NAME).then(cache=>{cache.addAll(event.data.urls||[]);});}});console.log(`[ServiceWorker]${APP_NAME}v${CACHE_VERSION}已加载`);